FORMAT: 1A
HOST: http://frozen-plateau-5382.herokuapp.com/api/

# mlbapi
MLB API is a database that holds Major League Baseball information by Player, Team, and Year.

# Group Player
Player related resources of the **MLB API**

## Players [/players]
### List all Players [GET]
+ Response 200 (application/json)
    
        [
            {
                "pk": 1,
                "fields": {
                    "throws": "R",
                    "bats": "L",
                    "number": 34,
                    "position": "OF",
                    "height": 74,
                    "name": "Bryce Harper",
                    "school": "College of Southern Nevada",
                    "social": "@Bharper3407",
                    "weight": 230
                },
                "model": "idb.player"
            },
            {
                "pk": 2,
                "fields": {
                    "throws": "R",
                    "bats": "R",
                    "number": 11,
                    "position": "P",
                    "height": 77,
                    "name": "Yu Darvish",
                    "school": "Sendai, Japan",
                    "social": "@faridyu",
                    "weight": 225
                },
                "model": "idb.player"
            },
            {
                "pk": 3,
                "fields": {
                    "throws": "R",
                    "bats": "R",
                    "number": 24,
                    "position": "1B",
                    "height": 76,
                    "name": "Miguel Cabrera",
                    "school": "Maracay, Venezuela",
                    "social": "@MiguelCabrera",
                    "weight": 240
                },
                "model": "idb.player"
            },
            {
                "pk": 4,
                "fields": {
                    "throws": "R",
                    "bats": "R",
                    "number": 35,
                    "position": "P",
                    "height": 77,
                    "name": "Justin Verlander",
                    "school": "Old Dominion University",
                    "social": "@JustinVerlander",
                    "weight": 225
                },
                "model": "idb.player"
            },
            {
                "pk": 5,
                "fields": {
                    "throws": "L",
                    "bats": "L",
                    "number": 22,
                    "position": "P",
                    "height": 75,
                    "name": "Clayton Kershaw",
                    "school": "Highland Park HS (Dallas, TX)",
                    "social": "@ClaytonKersh22",
                    "weight": 220
                },
                "model": "idb.player"
            },
            {
                "pk": 6,
                "fields": {
                    "throws": "R",
                    "bats": "R",
                    "number": 27,
                    "position": "OF",
                    "height": 74,
                    "name": "Mike Trout",
                    "school": "Millville Senior HS (Millville, NJ)",
                    "social": "@Trouty20",
                    "weight": 230
                },
                "model": "idb.player"
            },
            {
                "pk": 7,
                "fields": {
                    "throws": "R",
                    "bats": "R",
                    "number": 22,
                    "position": "OF",
                    "height": 61,
                    "name": "Andrew McCutchen",
                    "school": "Fort Meade HS (Fort Meade, FL)",
                    "social": "@TheCUTCH22",
                    "weight": 190
                },
                "model": "idb.player"
            },
            {
                "pk": 8,
                "fields": {
                    "throws": "R",
                    "bats": "R",
                    "number": 2,
                    "position": "SS",
                    "height": 75,
                    "name": "Derek Jeter",
                    "school": "Central HS (Kalamazoo, MI)",
                    "social": "",
                    "weight": 195
                },
                "model": "idb.player"
            },
            {
                "pk": 9,
                "fields": {
                    "throws": "L",
                    "bats": "L",
                    "number": 34,
                    "position": "1B",
                    "height": 76,
                    "name": "David Ortiz",
                    "school": "Haina, Dominican Republic",
                    "social": "@davidortiz",
                    "weight": 250
                },
                "model": "idb.player"
            },
            {
                "pk": 10,
                "fields": {
                    "throws": "R",
                    "bats": "R",
                    "number": 5,
                    "position": "1B",
                    "height": 75,
                    "name": "Albert Pujols",
                    "school": "Maple Woods Community College (Kansas City, MO)",
                    "social": "@PujolsFive",
                    "weight": 230
                },
                "model": "idb.player"
            },
            {
                "pk": 60,
                "fields": {
                    "throws": "L",
                    "bats": "R",
                    "number": 10,
                    "position": "OF",
                    "height": 74,
                    "name": "A Guy",
                    "school": "College of Southern Nevada",
                    "social": "@Bharper3407",
                    "weight": 230
                },
                "model": "idb.player"
            }
        ]

### Create a Player [POST]
+ Request (application/json)

        {
            "throws": "R",
            "bats": "L",
            "number": 34,
            "position": "OF",
            "height": 74,
            "name": "Bryce Harper",
            "school": "College of Southern Nevada",
            "social": "@Bharper3407",
            "weight": 230
        }

+ Response 201 (application/json)

        [
            {
                "pk": 1,
                "fields": {
                    "throws": "R",
                    "bats": "L",
                    "number": 34,
                    "position": "OF",
                    "height": 74,
                    "name": "Bryce Harper",
                    "school": "College of Southern Nevada",
                    "social": "@Bharper3407",
                    "weight": 230
                },
                "model": "idb.player"
            }
        ]

## Player [/players/{id}]
A single Player object with all its details

+ Parameters
    + id (required, number, `01`) ... Numeric `id` of the Player.

### Retrieve Information on a Player [GET]
+ Response 200 (application/json)

        [
            {
                "pk": 1,
                "fields": {
                    "throws": "R",
                    "bats": "L",
                    "number": 34,
                    "position": "OF",
                    "height": 74,
                    "name": "Bryce Harper",
                    "school": "College of Southern Nevada",
                    "social": "@Bharper3407",
                    "weight": 230
                },
                "model": "idb.player"
            }
        ]

### Modify a Player [PUT]
+ Request (application/json)

        {
            "position": "1B"
        }

+ Response 200 (application/json)

        [
            {
                "pk": 1,
                "fields": {
                    "throws": "R",
                    "bats": "L",
                    "number": 34,
                    "position": "1B",
                    "height": 74,
                    "name": "Bryce Harper",
                    "school": "College of Southern Nevada",
                    "social": "@Bharper3407",
                    "weight": 230
                },
                "model": "idb.player"
            }
        ]

### Delete a Player [DELETE]
+ Response 204

## Player Years [/players/{id}/years]
### List all the years that a player played [GET]
+ Response 200 (application/json)

        [
            {
                "pk": 1,
                "fields": {
                    "era": null,
                    "w": null,
                    "pa": 597,
                    "ip": null,
                    "s": null,
                    "team_year": 32,
                    "player": 1,
                    "obp": 0.34,
                    "avg": 0.27,
                    "games": 139,
                    "gs": null,
                    "year": 2012,
                    "hr": 22,
                    "l": null,
                    "slg": 0.477,
                    "rbi": 59,
                    "kind": "hitter",
                    "whip": null
                },
                "model": "idb.player_year"
            },
            {
                "pk": 2,
                "fields": {
                    "era": null,
                    "w": null,
                    "pa": 497,
                    "ip": null,
                    "s": null,
                    "team_year": 31,
                    "player": 1,
                    "obp": 0.368,
                    "avg": 0.274,
                    "games": 118,
                    "gs": null,
                    "year": 2013,
                    "hr": 20,
                    "l": null,
                    "slg": 0.486,
                    "rbi": 58,
                    "kind": "hitter",
                    "whip": null
                },
                "model": "idb.player_year"
            }
        ]
        
### Create a player year [POST]
+ Request (application/json)

        {
            "pa": 597,
            "team_year": 32,
            "player": 1,
            "obp": 0.34,
            "avg": 0.27,
            "games": 139,
            "year": 2012,
            "hr": 22,
            "slg": 0.477,
            "rbi": 59,
            "kind": "hitter"
        }

+ Response 201 (application/json)

        [
            {
                "pk": 1,
                "fields": {
                    "era": null,
                    "w": null,
                    "pa": 597,
                    "ip": null,
                    "s": null,
                    "team_year": 32,
                    "player": 1,
                    "obp": 0.34,
                    "avg": 0.27,
                    "games": 139,
                    "gs": null,
                    "year": 2012,
                    "hr": 22,
                    "l": null,
                    "slg": 0.477,
                    "rbi": 59,
                    "kind": "hitter",
                    "whip": null
                },
                "model": "idb.player_year"
            }
        ]
        
## Player Year [/players/{id}/years/{id}]
### Get details for a specific player year [GET]
+ Response 200 (application/json)

        [
            {
                "pk": 1,
                "fields": {
                    "era": null,
                    "w": null,
                    "pa": 597,
                    "ip": null,
                    "s": null,
                    "team_year": 32,
                    "player": 1,
                    "obp": 0.34,
                    "avg": 0.27,
                    "games": 139,
                    "gs": null,
                    "year": 2012,
                    "hr": 22,
                    "l": null,
                    "slg": 0.477,
                    "rbi": 59,
                    "kind": "hitter",
                    "whip": null
                },
                "model": "idb.player_year"
            }
        ]
        
### Modify a player year [PUT]
+ Request (application/json)

        {
            "games": 140,
        }

+ Response 200 (application/json)

        [
            {
                "pk": 1,
                "fields": {
                    "era": null,
                    "w": null,
                    "pa": 597,
                    "ip": null,
                    "s": null,
                    "team_year": 32,
                    "player": 1,
                    "obp": 0.34,
                    "avg": 0.27,
                    "games": 140,
                    "gs": null,
                    "year": 2012,
                    "hr": 22,
                    "l": null,
                    "slg": 0.477,
                    "rbi": 59,
                    "kind": "hitter",
                    "whip": null
                },
                "model": "idb.player_year"
            }
        ]
        
### Delete a Player Year [DELETE]
+ Response 204


# Group Team
Team related resources of the **MLB API**

## Teams [/teams]
### List all Teams [GET]
+ Response 200 (application/json)
    
        [
            {
                "pk": 2,
                "fields": {
                    "abbr": "STL",
                    "state": "MO",
                    "name": "St. Louis Cardinals",
                    "div": "NL Central",
                    "social": "@Cardinals",
                    "city": "St. Louis",
                    "mgr": "Mike Matheny",
                    "park": "Busch Stadium III"
                },
                "model": "idb.team"
            },
            {
                "pk": 3,
                "fields": {
                    "abbr": "LAD",
                    "state": "CA",
                    "name": "Los Angeles Dodgers",
                    "div": "NL West",
                    "social": "@Dodgers",
                    "city": "Los Angeles",
                    "mgr": "Don Mattingly",
                    "park": "Dodger Stadium"
                },
                "model": "idb.team"
            },
            {
                "pk": 4,
                "fields": {
                    "abbr": "WAS",
                    "state": "DC",
                    "name": "Washington Nationals",
                    "div": "NL East",
                    "social": "@Nationals",
                    "city": "Washington",
                    "mgr": "Matt Williams",
                    "park": "Nationals Park"
                },
                "model": "idb.team"
            },
            {
                "pk": 5,
                "fields": {
                    "abbr": "MIA",
                    "state": "FL",
                    "name": "Miami Marlins",
                    "div": "NL East",
                    "social": "@Marlins",
                    "city": "Miami",
                    "mgr": "Mike Redmond",
                    "park": "Marlins Park"
                },
                "model": "idb.team"
            },
            {
                "pk": 6,
                "fields": {
                    "abbr": "MIN",
                    "state": "MN",
                    "name": "Minnesota Twins",
                    "div": "AL Central",
                    "social": "@Twins",
                    "city": "Minneapolis",
                    "mgr": "Ron Gardenhire",
                    "park": "Target Field"
                },
                "model": "idb.team"
            },
            {
                "pk": 7,
                "fields": {
                    "abbr": "BOS",
                    "state": "MA",
                    "name": "Boston Red Sox",
                    "div": "AL East",
                    "social": "@RedSox",
                    "city": "Boston",
                    "mgr": "John Farrell",
                    "park": "Fenway Park"
                },
                "model": "idb.team"
            },
            {
                "pk": 8,
                "fields": {
                    "abbr": "NYY",
                    "state": "NY",
                    "name": "New York Yankees",
                    "div": "AL East",
                    "social": "@Yankees",
                    "city": "New York",
                    "mgr": "Joe Girardi",
                    "park": "Yankee Stadium III"
                },
                "model": "idb.team"
            },
            {
                "pk": 9,
                "fields": {
                    "abbr": "PIT",
                    "state": "PA",
                    "name": "Pittsburgh Pirates",
                    "div": "NL Central",
                    "social": "@Pirates",
                    "city": "Pittsburgh",
                    "mgr": "Clint Hurdle",
                    "park": "PNC Park"
                },
                "model": "idb.team"
            },
            {
                "pk": 10,
                "fields": {
                    "abbr": "DET",
                    "state": "MI",
                    "name": "Detroit Tigers",
                    "div": "AL Central",
                    "social": "@Tigers",
                    "city": "Detroit",
                    "mgr": "Brad Ausmus",
                    "park": "Comerica Park"
                },
                "model": "idb.team"
            },
            {
                "pk": 11,
                "fields": {
                    "abbr": "TEX",
                    "state": "TX",
                    "name": "Texas Rangers",
                    "div": "AL West",
                    "social": "@Rangers",
                    "city": "Dallas",
                    "mgr": "Ron Washington",
                    "park": "Rangers Ballpark"
                },
                "model": "idb.team"
            },
            {
                "pk": 1,
                "fields": {
                    "abbr": "LAA",
                    "state": "CA",
                    "name": "The Guy",
                    "div": "AL West",
                    "social": "@Angels",
                    "city": "Los Angeles",
                    "mgr": "Mike Scioscia",
                    "park": "Angel Stadium of Anaheim"
                },
                "model": "idb.team"
            }
        ]

### Create a Team [POST]
+ Request (application/json)

        {
            "abbr": "LAD",
            "state": "CA",
            "name": "Los Angeles Dodgers",
            "div": "NL West",
            "social": "@Dodgers",
            "city": "Los Angeles",
            "mgr": "Don Mattingly",
            "park": "Dodger Stadium"
        }

+ Response 201 (application/json)

        [
            {
                "pk": 12,
                "fields": {
                    "abbr": "LAD",
                    "state": "CA",
                    "name": "Los Angeles Dodgers",
                    "div": "NL West",
                    "social": "@Dodgers",
                    "city": "Los Angeles",
                    "mgr": "Don Mattingly",
                    "park": "Dodger Stadium"
                },
                "model": "idb.team"
            }
        ]

## Team [/teams/{id}]
A single Team object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Team.

### Retrieve Information on a Team [GET]
+ Response 200 (application/json)

        [
            {
                "pk": 1,
                "fields": {
                    "abbr": "LAA",
                    "state": "CA",
                    "name": "The Guy",
                    "div": "AL West",
                    "social": "@Angels",
                    "city": "Los Angeles",
                    "mgr": "Mike Scioscia",
                    "park": "Angel Stadium of Anaheim"
                },
                "model": "idb.team"
            }
        ]

### Modify a Team [PUT]
+ Request (application/json)

        {
            "social": "@LA_Angels"
        }

+ Response 200 (application/json)

        [
            {
                "pk": 1,
                "fields": {
                    "abbr": "LAA",
                    "state": "CA",
                    "name": "The Guy",
                    "div": "AL West",
                    "social": "@LA_Angels",
                    "city": "Los Angeles",
                    "mgr": "Mike Scioscia",
                    "park": "Angel Stadium of Anaheim"
                },
                "model": "idb.team"
            }
        ]

### Delete a Team [DELETE]
+ Response 204

## Team Years [/teams/{id}/years]
### List all the years that a team played [GET]
+ Response 200 (application/json)

        [
            {
                "pk": 1,
                "fields": {
                    "standing": 3,
                    "team": 1,
                    "wins": 78,
                    "attend": 3019505,
                    "payroll": 116032500,
                    "losses": 84,
                    "year": 2013,
                    "playoffs": ""
                },
                "model": "idb.team_year"
            },
            {
                "pk": 2,
                "fields": {
                    "standing": 3,
                    "team": 1,
                    "wins": 89,
                    "attend": 3061770,
                    "payroll": 140581000,
                    "losses": 73,
                    "year": 2012,
                    "playoffs": ""
                },
                "model": "idb.team_year"
            },
            {
                "pk": 3,
                "fields": {
                    "standing": 2,
                    "team": 1,
                    "wins": 86,
                    "attend": 3166321,
                    "payroll": 138543166,
                    "losses": 76,
                    "year": 2011,
                    "playoffs": ""
                },
                "model": "idb.team_year"
            },
            {
                "pk": 4,
                "fields": {
                    "standing": 3,
                    "team": 1,
                    "wins": 80,
                    "attend": 3250814,
                    "payroll": 104963866,
                    "losses": 82,
                    "year": 2010,
                    "playoffs": ""
                },
                "model": "idb.team_year"
            },
            {
                "pk": 5,
                "fields": {
                    "standing": 1,
                    "team": 1,
                    "wins": 97,
                    "attend": 3240386,
                    "payroll": 118169000,
                    "losses": 65,
                    "year": 2009,
                    "playoffs": "Lost ALCS (4-2)"
                },
                "model": "idb.team_year"
            },
            {
                "pk": 6,
                "fields": {
                    "standing": 1,
                    "team": 1,
                    "wins": 100,
                    "attend": 3336747,
                    "payroll": 119216333,
                    "losses": 62,
                    "year": 2008,
                    "playoffs": "Lost LDS (3-1)"
                },
                "model": "idb.team_year"
            },
            {
                "pk": 7,
                "fields": {
                    "standing": 1,
                    "team": 1,
                    "wins": 94,
                    "attend": 3365632,
                    "payroll": 109251333,
                    "losses": 68,
                    "year": 2007,
                    "playoffs": "Lost LDS (3-0)"
                },
                "model": "idb.team_year"
            },
            {
                "pk": 8,
                "fields": {
                    "standing": 2,
                    "team": 1,
                    "wins": 89,
                    "attend": 3406790,
                    "payroll": 103472000,
                    "losses": 73,
                    "year": 2006,
                    "playoffs": ""
                },
                "model": "idb.team_year"
            },
            {
                "pk": 9,
                "fields": {
                    "standing": 1,
                    "team": 1,
                    "wins": 95,
                    "attend": 3404686,
                    "payroll": 94867822,
                    "losses": 67,
                    "year": 2005,
                    "playoffs": "Lost ALCS (4-1)"
                },
                "model": "idb.team_year"
            },
            {
                "pk": 10,
                "fields": {
                    "standing": 1,
                    "team": 1,
                    "wins": 92,
                    "attend": 3375677,
                    "payroll": 100534667,
                    "losses": 70,
                    "year": 2004,
                    "playoffs": "Lost LDS (3-0)"
                },
                "model": "idb.team_year"
            }
        ]
        
### Create a team year [POST]
+ Request (application/json)

        {
            "standing": 1,
            "team": 1,
            "wins": 92,
            "attend": 3375677,
            "payroll": 100534667,
            "losses": 70,
            "year": 2014,
            "playoffs": "Lost LDS (3-0)"
        }

+ Response 201 (application/json)

        [
            {
                "pk": 11,
                "fields": {
                    "standing": 1,
                    "team": 1,
                    "wins": 92,
                    "attend": 3375677,
                    "payroll": 100534667,
                    "losses": 70,
                    "year": 2014,
                    "playoffs": "Lost LDS (3-0)"
                },
                "model": "idb.team_year"
            }
        ]
        
## Team Year [/teams/{id}/years/{id}]
### Get details for a specific team year [GET]
+ Response 200 (application/json)

        [
            {
                "pk": 1,
                "fields": {
                    "standing": 3,
                    "team": 1,
                    "wins": 78,
                    "attend": 3019505,
                    "payroll": 116032500,
                    "losses": 84,
                    "year": 2013,
                    "playoffs": ""
                },
                "model": "idb.team_year"
            }
        ]
        
### Modify a team year [PUT]
+ Request (application/json)

        {
            "wins": 79
        }

+ Response 200 (application/json)

        [
            {
                "pk": 1,
                "fields": {
                    "standing": 3,
                    "team": 1,
                    "wins": 79,
                    "attend": 3019505,
                    "payroll": 116032500,
                    "losses": 84,
                    "year": 2013,
                    "playoffs": ""
                },
                "model": "idb.team_year"
            }
        ]
        
### Delete a Team [DELETE]
+ Response 204

# Group Year
Year-related resources of the **MLB API**

## Years [/years]
### List all Years [GET]
+ Response 200 (application/json)

        [
            {
                "pk": 2004,
                "fields": {
                    "AL_MVP": "Vladimir Guerrero",
                    "NL_CY": "Roger Clemens",
                    "champion": "Boston Red Sox",
                    "AL_CY": "Johan Santana",
                    "year": "2004",
                    "NL_MVP": "Barry Bonds"
                },
                "model": "idb.year"
            },
            {
                "pk": 2005,
                "fields": {
                    "AL_MVP": "Alex Rodriguez",
                    "NL_CY": "Chris Carpenter",
                    "champion": "Chicago White Sox",
                    "AL_CY": "Bartolo Colon",
                    "year": "2005",
                    "NL_MVP": "Albert Pujols"
                },
                "model": "idb.year"
            },
            {
                "pk": 2006,
                "fields": {
                    "AL_MVP": "Justin Morneau",
                    "NL_CY": "Brandon Webb",
                    "champion": "St. Louis Cardinals",
                    "AL_CY": "Johan Santana",
                    "year": "2006",
                    "NL_MVP": "Ryan Howard"
                },
                "model": "idb.year"
            },
            {
                "pk": 2007,
                "fields": {
                    "AL_MVP": "Alex Rodriguez",
                    "NL_CY": "Jake Peavy",
                    "champion": "Boston Red Sox",
                    "AL_CY": "CC Sabathia",
                    "year": "2007",
                    "NL_MVP": "Jimmy Rollins"
                },
                "model": "idb.year"
            },
            {
                "pk": 2008,
                "fields": {
                    "AL_MVP": "Dustin Pedroia",
                    "NL_CY": "Tim Lincecum",
                    "champion": "Philadelphia Phillies",
                    "AL_CY": "Cliff Lee",
                    "year": "2008",
                    "NL_MVP": "Albert Pujols"
                },
                "model": "idb.year"
            },
            {
                "pk": 2009,
                "fields": {
                    "AL_MVP": "Joe Mauer",
                    "NL_CY": "Tim Lincecum",
                    "champion": "New York Yankees",
                    "AL_CY": "Zach Greinke",
                    "year": "2009",
                    "NL_MVP": "Albert Pujols"
                },
                "model": "idb.year"
            },
            {
                "pk": 2010,
                "fields": {
                    "AL_MVP": "Josh Hamilton",
                    "NL_CY": "Roy Halladay",
                    "champion": "San Francisco Giants",
                    "AL_CY": "Felix Hernandez",
                    "year": "2010",
                    "NL_MVP": "Joey Votto"
                },
                "model": "idb.year"
            },
            {
                "pk": 2011,
                "fields": {
                    "AL_MVP": "Justin Verlander",
                    "NL_CY": "Clayton Kershaw",
                    "champion": "St. Louis Cardinals",
                    "AL_CY": "Justin Verlander",
                    "year": "2011",
                    "NL_MVP": "Ryan Braun"
                },
                "model": "idb.year"
            },
            {
                "pk": 2012,
                "fields": {
                    "AL_MVP": "Miguel Cabrera",
                    "NL_CY": "RA Dickey",
                    "champion": "San Francisco Giants",
                    "AL_CY": "David Price",
                    "year": "2012",
                    "NL_MVP": "Buster Posey"
                },
                "model": "idb.year"
            },
            {
                "pk": 2013,
                "fields": {
                    "AL_MVP": "Miguel Cabrera",
                    "NL_CY": "Clayton Kershaw",
                    "champion": "Boston Red Sox",
                    "AL_CY": "Max Scherzer",
                    "year": "2013",
                    "NL_MVP": "Andrew McCutchen"
                },
                "model": "idb.year"
            },
            {
                "pk": 2050,
                "fields": {
                    "AL_MVP": "Migdf asCabrera",
                    "NL_CY": "Clayton Kershaw",
                    "champion": "hello",
                    "AL_CY": "Max Scherzer",
                    "year": "2050",
                    "NL_MVP": "Ddfsdf McCutchen"
                },
                "model": "idb.year"
            }
        ]

### Create a Year [POST]
+ Request (application/json)

        {
            "AL_MVP": "Miguel Cabrera",
            "NL_CY": "Clayton Kershaw",
            "champion": "Boston Red Sox",
            "AL_CY": "Max Scherzer",
            "year": "2014",
            "NL_MVP": "Andrew McCutchen"
        }

+ Response 201 (application/json)

        [
            {
                "pk": 2013,
                "fields": {
                    "AL_MVP": "Miguel Cabrera",
                    "NL_CY": "Clayton Kershaw",
                    "champion": "Boston Red Sox",
                    "AL_CY": "Max Scherzer",
                    "year": "2014",
                    "NL_MVP": "Andrew McCutchen"
                },
                "model": "idb.year"
            }
        ]

## Year [/years/{id}]
A single Year object with all its details

+ Parameters
    + id (required, number, `2013`) ... Numeric `id` of the Year.

### Retrieve Information on a Year [GET]
+ Response 200 (application/json)

        [
            {
                "pk": 2013,
                "fields": {
                    "AL_MVP": "Miguel Cabrera",
                    "NL_CY": "Clayton Kershaw",
                    "champion": "Boston Red Sox",
                    "AL_CY": "Max Scherzer",
                    "year": "2013",
                    "NL_MVP": "Andrew McCutchen"
                },
                "model": "idb.year"
            }
        ]

### Modify a Year [PUT]
+ Request (application/json)

        {
            "NL_MVP": "Ryan Braun"
        }

+ Response 200 (application/json)

        [
            {
                "pk": 2013,
                "fields": {
                    "AL_MVP": "Miguel Cabrera",
                    "NL_CY": "Clayton Kershaw",
                    "champion": "Boston Red Sox",
                    "AL_CY": "Max Scherzer",
                    "year": "2013",
                    "NL_MVP": "Ryan Braun"
                },
                "model": "idb.year"
            }
        ]

### Delete a Year [DELETE]
+ Response 204